<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;

class AiFeedback extends Model
{
    use HasFactory;

    protected $table = 'ai_feedback';

    protected $fillable = [
        'observation_id',
        'cot_rating_id',
        'feedback_type',
        'analysis',
        'recommendations',
        'strengths',
        'areas_for_improvement',
        'confidence_score',
        'model_version',
        'generated_by',
        'status',
        'reviewed_by',
        'reviewed_at',
    ];

    protected $casts = [
        'recommendations' => 'array',
        'strengths' => 'array',
        'areas_for_improvement' => 'array',
        'confidence_score' => 'decimal:2',
        'reviewed_at' => 'datetime',
    ];

    /**
     * STRICT SEPARATION:
     * This model is for AI-GENERATED feedback only.
     * For human/supervisor feedback, use Feedback model.
     */

    /**
     * AI Feedback belongs to an Observation
     */
    public function observation()
    {
        return $this->belongsTo(Observation::class);
    }

    /**
     * AI Feedback belongs to a COT Rating (nullable — for per-indicator feedback)
     */
    public function cotRating(): BelongsTo
    {
        return $this->belongsTo(CotRating::class);
    }

    /**
     * AI Feedback was reviewed by a User
     */
    public function reviewer()
    {
        return $this->belongsTo(User::class, 'reviewed_by');
    }

    /**
     * Check if AI feedback has high confidence
     */
    public function hasHighConfidence(): bool
    {
        return $this->confidence_score >= 0.85;
    }

    /**
     * Check if AI feedback has medium confidence
     */
    public function hasMediumConfidence(): bool
    {
        return $this->confidence_score >= 0.60 && $this->confidence_score < 0.85;
    }

    /**
     * Check if AI feedback needs review (low confidence)
     */
    public function needsReview(): bool
    {
        return $this->confidence_score < 0.60;
    }

    /**
     * Get formatted analysis
     */
    public function formattedAnalysis(): string
    {
        return nl2br(e($this->analysis));
    }

    /**
     * Scope for high confidence AI feedback
     */
    public function scopeHighConfidence($query)
    {
        return $query->where('confidence_score', '>=', 0.85);
    }

    /**
     * Scope for feedback by model version
     */
    public function scopeByModelVersion($query, string $version)
    {
        return $query->where('model_version', $version);
    }

    /**
     * Scope for a specific feedback type
     */
    public function scopeOfType($query, string $type)
    {
        return $query->where('feedback_type', $type);
    }

    /**
     * Scope for a specific status
     */
    public function scopeWithStatus($query, string $status)
    {
        return $query->where('status', $status);
    }

    /**
     * Scope only published feedback
     */
    public function scopePublished($query)
    {
        return $query->where('status', 'published');
    }

    /**
     * Scope only draft feedback
     */
    public function scopeDraft($query)
    {
        return $query->where('status', 'draft');
    }

    /**
     * Scope feedback generated by the supervisor (manual)
     */
    public function scopeManual($query)
    {
        return $query->where('generated_by', 'supervisor');
    }

    /**
     * Scope feedback generated by AI
     */
    public function scopeAiGenerated($query)
    {
        return $query->where('generated_by', 'ai');
    }

    /**
     * Check if feedback is published
     */
    public function isPublished(): bool
    {
        return $this->status === 'published';
    }

    /**
     * Check if feedback is a draft
     */
    public function isDraft(): bool
    {
        return $this->status === 'draft';
    }

    /**
     * Check if feedback was generated by the supervisor (manual entry)
     */
    public function isManual(): bool
    {
        return $this->generated_by === 'supervisor';
    }

    /**
     * Get the feedback type label
     */
    public function feedbackTypeLabel(): string
    {
        return match ($this->feedback_type) {
            'pre_observation' => 'Pre-Observation',
            'post_observation' => 'Post-Observation',
            'post_conference' => 'Post-Conference',
            'final_summary' => 'Final Summary',
            default => ucfirst(str_replace('_', ' ', $this->feedback_type ?? '')),
        };
    }

    /**
     * Get the status badge class
     */
    public function statusBadgeClass(): string
    {
        return match ($this->status) {
            'published' => 'bg-green-100 text-green-700',
            'draft' => 'bg-amber-100 text-amber-700',
            'archived' => 'bg-gray-100 text-gray-500',
            default => 'bg-gray-100 text-gray-600',
        };
    }

    /**
     * Get the generated-by badge class
     */
    public function generatedByBadgeClass(): string
    {
        return match ($this->generated_by) {
            'ai' => 'bg-purple-100 text-purple-700',
            'supervisor' => 'bg-blue-100 text-blue-700',
            'system' => 'bg-gray-100 text-gray-600',
            default => 'bg-gray-100 text-gray-600',
        };
    }

    /**
     * Publish this feedback
     */
    public function publish(?int $reviewedBy = null): void
    {
        $this->update([
            'status' => 'published',
            'reviewed_by' => $reviewedBy ?? auth()->id(),
            'reviewed_at' => now(),
        ]);
    }

    /**
     * Archive this feedback
     */
    public function archive(): void
    {
        $this->update(['status' => 'archived']);
    }
}
